### ISSUE TITLE
systemctl gives "failed to lookup unit file state"

### ISSUE THREAD

**Issue by kurt-klingbeil** [3cky/mbusd#24]
I managed to navigate all (most) of the installation song and dance on raspberry Pi (stretch)
but there are some loose ends...

When I try to run 
sudo systemctl enable mbusd@/dev/ttyAMA0.service
I get
Failed to lookup unit file state: Invalid argument

Apparently this is common with systemd / systemctl:
"you did it wrong and I'm not going to tell you anything about how"

I thought, well, if the default device is /dev/ttyS0 (whoever heard of AMA0?) I would try that.
Same thing.
I have gone through the song and dance of disabling serial port login and enabling serial port
and the port is available as shown by gpio readall
so presumeably there is some secret systemd incantation yet to be found...

I also expect some kind of port/register/IP-address mapping configuration 
like other TCP/RTU gateways so that the RTU-Master will poll via the serial connection,
and mbusd will then act as TCP-Master to retrieve data from the TCP-slave end-device

man -k mbusd turned up nothing appropriate, 
I looked for details in the doc/mbusd.8  file but there's nothing interesting in there...

It is now dawning on me that this is not a bidirectional gateway...
i.e. it is only a TCP-Slave which then acts as a RTU-master to get data from RTU-slave devices
which is the reverse of what I need

**Comment by 3cky** [comment]
> When I try to run
sudo systemctl enable mbusd@/dev/ttyAMA0.service
I get
Failed to lookup unit file state: Invalid argument

It's because it should be short device name, like `sudo systemctl enable mbusd@ttyAMA0.service`

> It is now dawning on me that this is not a bidirectional gateway...
i.e. it is only a TCP-Slave which then acts as a RTU-master to get data from RTU-slave devices
which is the reverse of what I need

Yep, mbusd is essentially a gateway presenting the network of RTU slaves as single TCP slave.
