### ISSUE TITLE
can this tool acts as a tcp client?

### ISSUE THREAD

**Issue by zouxiaodong** [3cky/mbusd#49]
i want to use mbusd to transfer modbus tcp to modbus rtu, could you add a feature that mbusd as a tcp client connect to iot server on internet? in many cases most of iot devices in LAN ，sever on internet

**Comment by nickma82** [comment]
> i want to use mbusd to transfer modbus tcp to modbus rtu

Well, that's exactly what it's supposed to do - see https://github.com/3cky/mbusd/issues/24#issuecomment-349256945

> could you add a feature that mbusd as a tcp client connect to iot server on internet

I'm not sure whether such a feature would belong into "gateway software" [see: [About mbusd](https://github.com/3cky/mbusd#about-mbusd)] or not, because its more of an application itself than a gateway feature.

What would be the target server and protocol? There are *a lot of* iot servers... Could you be more specific about what you'r trying to accomplish?
What other (e.g. those home automation servers [home-assistant](https://www.home-assistant.io/components/modbus/), [OpenHAB2](https://www.openhab.org/addons/bindings/modbus/)) are doing is that they poll data out of modbus devices by themselves - which too would work via WAN thanks to mbusd.
